version: '3'
services:
  iudex-tests:
    image: maven:3.8.4-openjdk-17
    container_name: maven-tests
    volumes:
      - ./src:/usr/src
      - ./pom.xml:/usr/pom.xml
      - ./DOCKERS:/usr/DOCKERS
    working_dir: /usr
    command: mvn test
    depends_on:
      - database
      - keycloak
      - rabbitmq
    environment:
      - spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
      - spring.datasource.url=jdbc:mysql://database:3306/testdb?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      - spring.datasource.username=iudexuser
      - spring.datasource.password=iudexpassword
      - spring.jpa.hibernate.ddl-auto=update
      - spring.rabbitmq.host=rabbit
      - spring.rabbitmq.port=5672
      - management.endpoint.health.show-details=always
      - logging.level.root=debug
    env_file:
      - secrets.env

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    ports:
      - "5672:5672"
    restart: always

  database:
    image: mysql:8
    container_name: database
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_HOST: database
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: testdb
      MYSQL_USER: iudexuser
      MYSQL_PASSWORD: iudexpassword
    restart: always

  keycloak:
    image: keycloak/keycloak:22.0
    container_name: keycloak
    ports:
      - "3000:8080"
    environment:
      KEYCLOAK_ADMIN: iudexci
      KEYCLOAK_ADMIN_PASSWORD: p455w0rd
    volumes:
      - ./keycloak-ci-realm.json:/opt/keycloak/data/import/realm.json
    command:
      - start-dev
      - --import-realm
      - --hostname-port=3000
    restart: always

volumes:
  db_data:
