name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Start RabbitMQ container
        run: docker run -p 5672:5672 -d --name conejito rabbitmq:3
      - name: Start Database container
        run: docker run --name bbdd -v db_data:/var/lib/mysql -p 3306:3306 -e MYSQL_HOST=bbdd -e MYSQL_RANDOM_ROOT_PASSWORD=yes -e MYSQL_DATABASE=testdb -e MYSQL_USER=iudexuser -e MYSQL_PASSWORD=iudexpassword -d mysql:8
      - name: Start Keycloak Server
        run: docker run -p 3000:8080 -e KEYCLOAK_ADMIN=iudexci -e KEYCLOAK_ADMIN_PASSWORD=p455w0rd -v $(pwd)/keycloak-ci-realm.json:/opt/keycloak/data/import/realm.json -d keycloak/keycloak:22.0 start-dev --import-realm --hostname-port=3000 && sleep 60
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENTID: ${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENTID }}
          SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENTSECRET: ${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENTSECRET }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
